replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/my-gcp-project/hello-gke/worker
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""
