{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s" .Chart.Name) .Values.serviceAccount.name }}
  labels:
    {{- include "hello-gke.labels" . | nindent 4 }}
{{- end }}
